## Hands on practice: Linear Algebra for AI

### Exercise 1: Working with scalars and vectors

In [ ]:
import numpy as np

In [ ]:
#Creating a scalar
scaler  = 7

#Creating a vector
vector = np.array([3,5,7])
print("Vector:", vector)

#Scaling vector through a scalar aka scaled vector
scaled_vector = scaler * vector
print("Scaled vector:", scaled_vector)

Vector: [3 5 7]
Scaled vector: [21 35 49]


## Exercise 2: Addition and subtraction

In [ ]:
vector1 = np.array([3, 6, 12])
vector2 = np.array([5, 2, 15])

add_vector = vector1 + vector2
subtract_vector = vector1 - vector2

print("Added vector:", add_vector)
print("Subtracted vector:", subtract_vector)

Added vector: [ 8  8 27]
Subtracted vector: [-2  4 -3]


## Exercise 3: Matrix creation and basic creation

In [ ]:
matrix1 = np.array([[2, 4], [5,7]])
matrix2 = np.array([[6,8],[9,11]])
print(matrix1 + matrix2)
print(matrix1 - matrix2)

[[ 8 12]
 [14 18]]
[[-4 -4]
 [-4 -4]]


## Exercise 4: Matrix multiplication

In [ ]:
product = np.dot(matrix1, matrix2)
print(product)

[[ 48  60]
 [ 93 117]]


In [ ]:
mat1 = np.array([[1,2,3], [5,7,9], [2,0,1]])
mat2 = np.array([[0,1,2], [1,3,4], [0,2,1]])

prod1 = np.dot(mat1, mat2)
print(prod1)

[[ 2 13 13]
 [ 7 44 47]
 [ 0  4  5]]


In [ ]:
A = np.array([[1,3], [9,3]])
squared = np.dot(A, A)
print(squared)

[[28 12]
 [36 36]]


In [ ]:
#Implementing matrix multiplication from scratch

matrix1 = np.array([[2, 4], [5,7]])
matrix2 = np.array([[6,8],[9,11]])

index_0_0 = (matrix1[0,0] * matrix2[0,0]) + (matrix1[0,1] * matrix2[1,0])
index_0_1 = (matrix1[0,0] * matrix2[0,1]) + (matrix1[0,1] * matrix2[1,1])
index_1_0 = (matrix1[1,0] * matrix2[0,0]) + (matrix1[1,1] * matrix2[1,0])
index_1_1 = (matrix1[1,0] * matrix2[0,1]) + (matrix1[1,1] * matrix2[1,1])

print(index_0_0)
print(index_0_1)
print(index_1_0)
print(index_1_1)

product1 = np.array([[index_0_0, index_0_1], [index_1_0, index_1_1]])
print(product1)

product2 = np.dot(matrix1, matrix2)
print(product2)

48
60
93
117
[[ 48  60]
 [ 93 117]]
[[ 48  60]
 [ 93 117]]


## Exercise 5: Identity matrix and transpose

In [ ]:
## Indentity matrix

identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Transpose

matrix1 = np.array([[2, 4], [5,7]])
tranpose1 = matrix1.T
print(tranpose1)

[[2 5]
 [4 7]]


##Homework

In [2]:
## 1. vector [7,8,9] and multiply by 2

import numpy as np
#Creating a scalar
scaler  = 2

#Creating a vector
vector = np.array([7,8,9])
print("Vector:", vector)

#Scaling vector through a scalar aka scaled vector
scaled_vector = scaler * vector
print("Scaled vector:", scaled_vector)

Vector: [7 8 9]
Scaled vector: [14 16 18]


In [3]:
# two vectors [3,4] and [1,2], print sum and diff

matrix1 = np.array([3,4])
matrix2 = np.array([1,2])
print(matrix1 + matrix2)
print(matrix1 - matrix2)

[4 6]
[2 2]


In [4]:
# two 2x2 [[0,1], [2,3]] and [[4,5], [6,7]]. find sum

matrix1 = np.array([[0,1], [2,3]])
matrix2 = np.array([[4,5], [6,7]])
print(matrix1 + matrix2)

[[ 4  6]
 [ 8 10]]


In [5]:
## two 2x2 matrices [[2,1], [0,3]] and [[1,2], [3,4]] and find product

matrix1 = np.array([[2, 1], [0,3]])
matrix2 = np.array([[1,2],[3,4]])

product2 = np.dot(matrix1, matrix2)
print(product2)

[[ 5  8]
 [ 9 12]]


In [6]:
## 2x 3 matrix and print transpose and 3x3 identity matrix

mat = np.array([[5,10,15], [20, 25, 30]])

trans_mat = mat.T
print(trans_mat)

[[ 5 20]
 [10 25]
 [15 30]]


In [7]:
iden_mat = np.eye(3)
print(iden_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
